/**
 * Global Variables
 */
const PROJECT_ID = 'TODO';
const OAUTH_CLIENT_ID = 'TODO';
const OAUTH_CLIENT_SECRET = 'TODO';
const DOWNSTAIRS_THERMOSTAT = 'XXXXXXXXXXXXXXXXXX';
const UPSTAIRS_THERMOSTAT = 'XXXXXXXXXXXXXXXXXX';
const APIKEY = 'TODO';
const CITYID = 'TODO' ;
